//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Estudiantil
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiantes
    {
        public long matricula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string sexo { get; set; }
        public string identificacion { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    }
}
